export type ChemistryQuestion = {
  id: string;
  specTags: string[];
  summary: string;
  marks: number;
  year: number;
  session: string;
  paper: "1C" | "2C";
  questionNumber: number;
  sourceFile: string;
};

export const chemistryQuestions: ChemistryQuestion[] = [
  { id:"chem-2025-1C-1", specTags:["1c","1d"], summary:"Atomic structure: subatomic particles, mass number, group, period, electronic configuration and element identification.", marks:8, year:2025, session:"May/June", paper:"1C", questionNumber:1, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-2", specTags:["2a","2f","2h"], summary:"Lithium reacting with water, alkaline solution and pH, hydroxide ions, and the lithium flame test.", marks:8, year:2025, session:"May/June", paper:"1C", questionNumber:2, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-3", specTags:["1b"], summary:"Paper chromatography: pencil start line, solubility, interpreting spots and calculating an Rf value.", marks:11, year:2025, session:"May/June", paper:"1C", questionNumber:3, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-4", specTags:["1e","1f"], summary:"Calcium phosphate: ionic charges, relative formula mass, percentage composition and balancing a reaction equation.", marks:7, year:2025, session:"May/June", paper:"1C", questionNumber:4, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-5", specTags:["4a","4b","4c"], summary:"Butane and alkanes: saturated hydrocarbons, combustion, carbon monoxide, isomers and boiling-point trends.", marks:14, year:2025, session:"May/June", paper:"1C", questionNumber:5, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-6", specTags:["2d","2h","1e"], summary:"Iron rusting and reactivity, galvanising, Fe3+ chemical test, redox, reacting masses and percentage yield.", marks:13, year:2025, session:"May/June", paper:"1C", questionNumber:6, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-7", specTags:["2f","3a"], summary:"Neutralisation experiment: equation and state symbols, improving accuracy, plotting results, anomalies and maximum temperature change.", marks:12, year:2025, session:"May/June", paper:"1C", questionNumber:7, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-8", specTags:["1g"], summary:"Giant covalent structures: explain the melting point of diamond and the softness and electrical conductivity of graphite.", marks:9, year:2025, session:"May/June", paper:"1C", questionNumber:8, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-9", specTags:["1g","1e","4a","4c","4d","4h"], summary:"Organic compounds: covalent bonding, chloroethene and polymers, empirical formula, and reactions of ethane and ethene with bromine.", marks:17, year:2025, session:"May/June", paper:"1C", questionNumber:9, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },
  { id:"chem-2025-1C-10", specTags:["3a","4e"], summary:"Fuel calorimetry using ethanol: control variables, heat energy change and molar enthalpy change.", marks:11, year:2025, session:"May/June", paper:"1C", questionNumber:10, sourceFile:"May_June_2025_Chemistry_Paper_1C_ExamWizard_Style.docx" },

  { id:"chem-2025-2C-1", specTags:["1b","4b"], summary:"Classifying elements, compounds and mixtures, diatomic molecules, and fractional distillation and uses of crude-oil fractions.", marks:6, year:2025, session:"May/June", paper:"2C", questionNumber:1, sourceFile:"May_June_2025_Chemistry_Paper_2C_ExamWizard_Style.docx.docx" },
  { id:"chem-2025-2C-2", specTags:["1e","2d","3a","3b"], summary:"Magnesium and hydrochloric acid: exothermic reaction, equation, rate graph, collision theory and reaction profile.", marks:13, year:2025, session:"May/June", paper:"2C", questionNumber:2, sourceFile:"May_June_2025_Chemistry_Paper_2C_ExamWizard_Style.docx.docx" },
  { id:"chem-2025-2C-3", specTags:["1c","1f","1i","2g"], summary:"Magnesium isotopes and relative atomic mass, solubility, ionic structure and conductivity, and electrolysis of magnesium chloride.", marks:16, year:2025, session:"May/June", paper:"2C", questionNumber:3, sourceFile:"May_June_2025_Chemistry_Paper_2C_ExamWizard_Style.docx.docx" },
  { id:"chem-2025-2C-4", specTags:["4e","4f","4g"], summary:"Ethanol oxidation, reactions of ethanoic acid and preparation and identification of the ester ethyl ethanoate.", marks:12, year:2025, session:"May/June", paper:"2C", questionNumber:4, sourceFile:"May_June_2025_Chemistry_Paper_2C_ExamWizard_Style.docx.docx" },
  { id:"chem-2025-2C-5", specTags:["1e","2f","2g"], summary:"Acid-alkali titration: apparatus, burette readings, concordant titres, concentration calculation and preparation of pure dry crystals.", marks:13, year:2025, session:"May/June", paper:"2C", questionNumber:5, sourceFile:"May_June_2025_Chemistry_Paper_2C_ExamWizard_Style.docx.docx" },
  { id:"chem-2025-2C-6", specTags:["1e","2h","3c"], summary:"Hydrogen and iodine equilibrium: gas test, reversible reaction symbol, effects of temperature and pressure, yield and gas-volume calculation.", marks:10, year:2025, session:"May/June", paper:"2C", questionNumber:6, sourceFile:"May_June_2025_Chemistry_Paper_2C_ExamWizard_Style.docx.docx" },

  { id:"chem-2025-nov-1C-1", specTags:["1a"], summary:"States of matter: particle arrangements, changes of state and equations with state symbols.", marks:7, year:2025, session:"November", paper:"1C", questionNumber:1, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-2", specTags:["2c","1e"], summary:"Gases in the atmosphere: identifying atmospheric gases, thermal decomposition of copper(II) carbonate and estimating the percentage of oxygen in air.", marks:8, year:2025, session:"November", paper:"1C", questionNumber:2, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-3", specTags:["1c","1d"], summary:"Atomic structure and the Periodic Table: subatomic particles, ions, group and period numbers, element symbols and trends in relative atomic mass.", marks:11, year:2025, session:"November", paper:"1C", questionNumber:3, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-4", specTags:["1f","2h","1a"], summary:"Ammonium chloride: chloride-ion electron arrangement, chemical tests for ammonium/chloride/sulfate ions, diffusion and state symbols.", marks:12, year:2025, session:"November", paper:"1C", questionNumber:4, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-5", specTags:["2d","3a"], summary:"Displacement reactions of metals with copper(II) sulfate: practical variables, temperature changes, anomalies and comparing metal reactivity.", marks:13, year:2025, session:"November", paper:"1C", questionNumber:5, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-6", specTags:["4b","4c","4d","4h"], summary:"Crude oil and organic chemistry: fractional distillation, cracking, octane as a fuel and addition polymerisation of ethene.", marks:15, year:2025, session:"November", paper:"1C", questionNumber:6, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-7", specTags:["2f","3a"], summary:"Neutralisation calorimetry: interpreting temperature-volume graphs, identifying mistakes, heat-energy calculations and enthalpy change.", marks:12, year:2025, session:"November", paper:"1C", questionNumber:7, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-8", specTags:["1f"], summary:"Ionic compounds: writing formulae from ions and explaining melting points using ionic structure and bonding.", marks:8, year:2025, session:"November", paper:"1C", questionNumber:8, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-9", specTags:["4a","4c","4d","1g","1e"], summary:"Propene and propane: formulae, dot-and-cross bonding, bromine reactions, empirical formula calculations, functional groups and isomerism.", marks:12, year:2025, session:"November", paper:"1C", questionNumber:9, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2025-nov-1C-10", specTags:["1e","2g","2d","3b"], summary:"Preparing aluminium sulfate crystals: excess reactant, filtration and crystallisation, effect of surface area, reacting amounts and percentage yield.", marks:12, year:2025, session:"November", paper:"1C", questionNumber:10, sourceFile:"November_2025_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },

  { id:"chem-2025-nov-2C-1", specTags:["2f","2g"], summary:"Laboratory apparatus: identifying a burette and choosing apparatus for titration, measuring volumes and evaporating solvent to form crystals.", marks:7, year:2025, session:"November", paper:"2C", questionNumber:1, sourceFile:"November_2025_Chemistry_Paper_2C_ExamWizard_Style.docx" },
  { id:"chem-2025-nov-2C-2", specTags:["2b","1c","1e"], summary:"Group 7 halogens: states and colours, relative atomic mass and molecular probabilities, plus displacement reactions and the trend in reactivity.", marks:15, year:2025, session:"November", paper:"2C", questionNumber:2, sourceFile:"November_2025_Chemistry_Paper_2C_ExamWizard_Style.docx" },
  { id:"chem-2025-nov-2C-3", specTags:["2d","2e","1e","1i"], summary:"Iron, steel and zinc: rust prevention, malleability and uses, reacting masses and gas volume, plus electrolysis and redox half-equations.", marks:15, year:2025, session:"November", paper:"2C", questionNumber:3, sourceFile:"November_2025_Chemistry_Paper_2C_ExamWizard_Style.docx" },
  { id:"chem-2025-nov-2C-4", specTags:["4e","4g","4h"], summary:"Ethanol manufacture and fermentation, ester formation, and condensation polymerisation to make a polyester.", marks:14, year:2025, session:"November", paper:"2C", questionNumber:4, sourceFile:"November_2025_Chemistry_Paper_2C_ExamWizard_Style.docx" },
  { id:"chem-2025-nov-2C-5", specTags:["3b","2h"], summary:"Hydrogen peroxide decomposition: testing for water, interpreting rate curves and comparing manganese(IV) oxide with potassium iodide as catalysts.", marks:11, year:2025, session:"November", paper:"2C", questionNumber:5, sourceFile:"November_2025_Chemistry_Paper_2C_ExamWizard_Style.docx" },
  { id:"chem-2025-nov-2C-6", specTags:["4c","3a"], summary:"Methane chlorination: substitution reactions, reaction profiles, activation energy and calculating a bond energy from bond-energy data.", marks:8, year:2025, session:"November", paper:"2C", questionNumber:6, sourceFile:"November_2025_Chemistry_Paper_2C_ExamWizard_Style.docx" },
];
