import type { ChemistryQuestion } from "./chemistryQuestions";

export const chemistryQuestions2024: ChemistryQuestion[] = [
  { id:"chem-2024-nov-1C-1", specTags:["1a"], summary:"States of matter: changes of state, particle arrangements in solids, liquids and gases, and state symbols for freezing water.", marks:6, year:2024, session:"November", paper:"1C", questionNumber:1, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-2", specTags:["2c","2h","1b","1g"], summary:"Common gases: combustion and air composition, chlorine test, compounds, and intermolecular forces affecting boiling point.", marks:6, year:2024, session:"November", paper:"1C", questionNumber:2, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-3", specTags:["2d"], summary:"Rusting of iron: conditions required, rust, barrier protection and galvanising with zinc.", marks:8, year:2024, session:"November", paper:"1C", questionNumber:3, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-4", specTags:["1b"], summary:"Paper chromatography: experimental method, insoluble dyes, matching spots and determining Rf values.", marks:11, year:2024, session:"November", paper:"1C", questionNumber:4, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-5", specTags:["2h","3b"], summary:"Hydrogen peroxide decomposition: oxygen test, catalysts, gas-collection apparatus, interpreting a rate graph and drawing a tangent.", marks:11, year:2024, session:"November", paper:"1C", questionNumber:5, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-6", specTags:["1f","1g"], summary:"Ionic and covalent compounds: ionic formulae, electron transfer in magnesium chloride, ammonia dot-and-cross diagrams and covalent attraction.", marks:11, year:2024, session:"November", paper:"1C", questionNumber:6, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-7", specTags:["1a","1e","2h"], summary:"Hydrated magnesium sulfate: water of crystallisation, testing for water and calculating the hydration number from mass data.", marks:8, year:2024, session:"November", paper:"1C", questionNumber:7, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-8", specTags:["3b"], summary:"Rate of reaction between marble chips and hydrochloric acid: mass loss, limiting reactants, controls and temperature effects using collision theory.", marks:9, year:2024, session:"November", paper:"1C", questionNumber:8, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-9", specTags:["3a","4e","1e"], summary:"Fuel calorimetry with ethanol and butanol: heat-energy calculations, molar enthalpy change, incomplete combustion and reacting-amount calculations.", marks:13, year:2024, session:"November", paper:"1C", questionNumber:9, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-10", specTags:["4a","4c","4d","4h"], summary:"Alkanes and alkenes: substitution and addition with bromine, homologous series, isomerism and addition polymerisation of ethene.", marks:12, year:2024, session:"November", paper:"1C", questionNumber:10, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-1C-11", specTags:["2e","2c","1e","1f","1g"], summary:"Lead compounds: extraction from lead sulfide, sulfur dioxide pollution, reacting masses, ionic versus simple molecular structures and empirical formula.", marks:15, year:2024, session:"November", paper:"1C", questionNumber:11, sourceFile:"November_2024_Chemistry_Paper_1C_ExamWizard_Style_FINAL.docx" },

  { id:"chem-2024-nov-2C-1", specTags:["1c"], summary:"Atomic structure: atoms and ions, full outer shells, atomic and mass numbers, isotopes and calculating nuclear mass.", marks:7, year:2024, session:"November", paper:"2C", questionNumber:1, sourceFile:"November_2024_Chemistry_Paper_2C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-2C-2", specTags:["1h","2e","2h"], summary:"Metals and metal compounds: metallic bonding, malleability and conductivity, extracting iron and distinguishing iron(II) from iron(III) ions.", marks:8, year:2024, session:"November", paper:"2C", questionNumber:2, sourceFile:"November_2024_Chemistry_Paper_2C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-2C-3", specTags:["1b"], summary:"Separating ethanol and water by fractional distillation: identifying apparatus and testing purity using a physical property.", marks:6, year:2024, session:"November", paper:"2C", questionNumber:3, sourceFile:"November_2024_Chemistry_Paper_2C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-2C-4", specTags:["2a","2f","1e"], summary:"Group 1 metals: lithium and potassium reacting with water, alkaline solutions, gas-volume calculations and the trend in reactivity.", marks:11, year:2024, session:"November", paper:"2C", questionNumber:4, sourceFile:"November_2024_Chemistry_Paper_2C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-2C-5", specTags:["2f","2g"], summary:"Acid-alkali titration: apparatus, indicator choice, burette readings, concordant titres and preparing pure dry sodium nitrate crystals.", marks:13, year:2024, session:"November", paper:"2C", questionNumber:5, sourceFile:"November_2024_Chemistry_Paper_2C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-2C-6", specTags:["4b","4d","3a"], summary:"Crude oil and cracking: fractional distillation, cracking conditions and uses, plus ethene-bromine bond-energy and enthalpy calculations.", marks:13, year:2024, session:"November", paper:"2C", questionNumber:6, sourceFile:"November_2024_Chemistry_Paper_2C_ExamWizard_Style_FINAL.docx" },
  { id:"chem-2024-nov-2C-7", specTags:["4e","4f","4g","4h","1e"], summary:"Alcohols and carboxylic acids: naming and formulae, ester formation, neutralisation calculations and condensation polymerisation to make a polyester.", marks:12, year:2024, session:"November", paper:"2C", questionNumber:7, sourceFile:"November_2024_Chemistry_Paper_2C_ExamWizard_Style_FINAL.docx" },
];
