import type { Question } from "./questions";

export const physicsQuestions: Question[] = [
  { id:"phys-2025-nov-1P-1",year:2025,session:"November",paper:"1P",questionNumber:1,marks:7,topics:["8c","8b"],difficulty:"Medium",summary:"Stellar colour and evolution, then orbital speed in a binary star system." },
  { id:"phys-2025-nov-1P-2",year:2025,session:"November",paper:"1P",questionNumber:2,marks:5,topics:["1b","1c"],difficulty:"Easy",summary:"Average speed, thinking distance, braking distance and stopping-distance factors." },
  { id:"phys-2025-nov-1P-3",year:2025,session:"November",paper:"1P",questionNumber:3,marks:6,topics:["2b"],difficulty:"Medium",summary:"Domestic wiring, circuit breakers, fuses and earthing." },
  { id:"phys-2025-nov-1P-4",year:2025,session:"November",paper:"1P",questionNumber:4,marks:6,topics:["4c","4b"],difficulty:"Medium",summary:"Work done, gravitational energy and conservation of energy on a ramp." },
  { id:"phys-2025-nov-1P-5",year:2025,session:"November",paper:"1P",questionNumber:5,marks:10,topics:["7b"],difficulty:"Medium",summary:"Alpha and beta decay, radiation safety and mean count rate." },
  { id:"phys-2025-nov-1P-6",year:2025,session:"November",paper:"1P",questionNumber:6,marks:16,topics:["6b","6c"],difficulty:"Hard",summary:"Magnetic fields and materials, then the force on a current-carrying wire investigation." },
  { id:"phys-2025-nov-1P-7",year:2025,session:"November",paper:"1P",questionNumber:7,marks:12,topics:["2c"],difficulty:"Hard",summary:"Voltage, current, resistance, LDR behaviour and parallel resistors." },
  { id:"phys-2025-nov-1P-8",year:2025,session:"November",paper:"1P",questionNumber:8,marks:9,topics:["5b"],difficulty:"Medium",summary:"Measuring volume and mass, then using density to determine liquid volume." },
  { id:"phys-2025-nov-1P-9",year:2025,session:"November",paper:"1P",questionNumber:9,marks:7,topics:["1b"],difficulty:"Medium",summary:"Velocity-time graphs, acceleration and distance from area under a graph." },
  { id:"phys-2025-nov-1P-10",year:2025,session:"November",paper:"1P",questionNumber:10,marks:11,topics:["3b","3d"],difficulty:"Hard",summary:"Wave definition, reflection, critical angle, refractive index and total internal reflection." },
  { id:"phys-2025-nov-1P-11",year:2025,session:"November",paper:"1P",questionNumber:11,marks:5,topics:["4b"],difficulty:"Medium",summary:"Convection-current explanation using a smoke-box demonstration." },
  { id:"phys-2025-nov-1P-12",year:2025,session:"November",paper:"1P",questionNumber:12,marks:16,topics:["5d","5b"],difficulty:"Hard",summary:"Gas particles and pressure, manometers, pressure difference and gas laws." },

  { id:"phys-2025-nov-2P-1",year:2025,session:"November",paper:"2P",questionNumber:1,marks:6,topics:["2d","1c"],difficulty:"Medium",summary:"Electric charge, Newton's third law and moments about a pivot." },
  { id:"phys-2025-nov-2P-2",year:2025,session:"November",paper:"2P",questionNumber:2,marks:6,topics:["8b"],difficulty:"Medium",summary:"Gravitational field strength, planetary diameter and mass." },
  { id:"phys-2025-nov-2P-3",year:2025,session:"November",paper:"2P",questionNumber:3,marks:11,topics:["1c","4b","4d"],difficulty:"Hard",summary:"Momentum and force through a turbine, energy transfers and renewable/non-renewable resources." },
  { id:"phys-2025-nov-2P-4",year:2025,session:"November",paper:"2P",questionNumber:4,marks:9,topics:["3d"],difficulty:"Hard",summary:"Measuring sound frequency with an oscilloscope, period and frequency." },
  { id:"phys-2025-nov-2P-5",year:2025,session:"November",paper:"2P",questionNumber:5,marks:9,topics:["6c","6d"],difficulty:"Hard",summary:"Solenoid field direction and transformer voltage, type and alternating current." },
  { id:"phys-2025-nov-2P-6",year:2025,session:"November",paper:"2P",questionNumber:6,marks:7,topics:["8d"],difficulty:"Hard",summary:"Galaxy red-shift, recession velocity and cosmic microwave background evidence." },
  { id:"phys-2025-nov-2P-7",year:2025,session:"November",paper:"2P",questionNumber:7,marks:9,topics:["5c"],difficulty:"Hard",summary:"Heating and melting a metal, specific heat capacity and particle motion in gases." },
  { id:"phys-2025-nov-2P-8",year:2025,session:"November",paper:"2P",questionNumber:8,marks:13,topics:["7c","7b"],difficulty:"Hard",summary:"Nuclear fission chain reactions, fusion, radioactive decay and half-life." },

  // May/June 2025 Paper 1P
  { id:"phys-2025-mj-1P-1",year:2025,session:"May/June",paper:"1P",questionNumber:1,marks:7,topics:["1b","1c"],difficulty:"Easy",summary:"Average speed and distance, then friction and its effect on velocity." },
  { id:"phys-2025-mj-1P-2",year:2025,session:"May/June",paper:"1P",questionNumber:2,marks:13,topics:["8b","8c"],difficulty:"Medium",summary:"Orbital paths, gravity, galaxies, stellar colour and stellar evolution." },
  { id:"phys-2025-mj-1P-3",year:2025,session:"May/June",paper:"1P",questionNumber:3,marks:15,topics:["2c"],difficulty:"Hard",summary:"Thermistors, voltage, current and resistance, then calibrating a temperature-measuring circuit." },
  { id:"phys-2025-mj-1P-4",year:2025,session:"May/June",paper:"1P",questionNumber:4,marks:8,topics:["7c"],difficulty:"Medium",summary:"Controlled nuclear fission, chain reactions and reactor control." },
  { id:"phys-2025-mj-1P-5",year:2025,session:"May/June",paper:"1P",questionNumber:5,marks:6,topics:["6c"],difficulty:"Medium",summary:"How a direct-current motor turns continuously using brushes and a split-ring commutator." },
  { id:"phys-2025-mj-1P-6",year:2025,session:"May/June",paper:"1P",questionNumber:6,marks:12,topics:["4b","4c"],difficulty:"Medium",summary:"An experiment to determine power while running upstairs, including energy transfer and measurement." },
  { id:"phys-2025-mj-1P-7",year:2025,session:"May/June",paper:"1P",questionNumber:7,marks:7,topics:["5b"],difficulty:"Medium",summary:"Pressure in liquids and gases, including forces on bubbles and pressure changes with depth." },
  { id:"phys-2025-mj-1P-8",year:2025,session:"May/June",paper:"1P",questionNumber:8,marks:11,topics:["3b"],difficulty:"Medium",summary:"Ripple-tank waves, transverse waves, wavelength, frequency and wave behaviour." },
  { id:"phys-2025-mj-1P-9",year:2025,session:"May/June",paper:"1P",questionNumber:9,marks:8,topics:["7b"],difficulty:"Medium",summary:"Protactinium-234m radioactivity, radiation detection, safety and decay measurements." },
  { id:"phys-2025-mj-1P-10",year:2025,session:"May/June",paper:"1P",questionNumber:10,marks:11,topics:["6c"],difficulty:"Hard",summary:"Investigating the magnetic force on a current-carrying conductor using a balance." },
  { id:"phys-2025-mj-1P-11",year:2025,session:"May/June",paper:"1P",questionNumber:11,marks:12,topics:["2c","7b"],difficulty:"Hard",summary:"Fluorescent tube lamps, voltage and current, ionisation and energy transfers." },

  // May/June 2025 Paper 2P
  { id:"phys-2025-mj-2P-1",year:2025,session:"May/June",paper:"2P",questionNumber:1,marks:7,topics:["5b"],difficulty:"Medium",summary:"Measuring mass and irregular volume by displacement, then calculating density." },
  { id:"phys-2025-mj-2P-2",year:2025,session:"May/June",paper:"2P",questionNumber:2,marks:6,topics:["3d"],difficulty:"Medium",summary:"Sound-wave frequency range, wave properties and oscilloscope traces." },
  { id:"phys-2025-mj-2P-3",year:2025,session:"May/June",paper:"2P",questionNumber:3,marks:9,topics:["4b","4d","2d"],difficulty:"Medium",summary:"Solar energy transfers, renewable generation, thermal absorption and charge transfer." },
  { id:"phys-2025-mj-2P-4",year:2025,session:"May/June",paper:"2P",questionNumber:4,marks:9,topics:["1c"],difficulty:"Medium",summary:"Moments and the principle of moments applied to a spring-loaded gate mechanism." },
  { id:"phys-2025-mj-2P-5",year:2025,session:"May/June",paper:"2P",questionNumber:5,marks:12,topics:["2d"],difficulty:"Hard",summary:"Static electricity, charge transfer, electrostatic forces and an inverse-square relationship investigation." },
  { id:"phys-2025-mj-2P-6",year:2025,session:"May/June",paper:"2P",questionNumber:6,marks:5,topics:["7b"],difficulty:"Medium",summary:"Gamma radiation, ionisation, penetration and the inverse-square law." },
  { id:"phys-2025-mj-2P-7",year:2025,session:"May/June",paper:"2P",questionNumber:7,marks:14,topics:["6d","4b"],difficulty:"Hard",summary:"Transformer turns ratio, efficiency and the use of transformers in power transmission." },
  { id:"phys-2025-mj-2P-8",year:2025,session:"May/June",paper:"2P",questionNumber:8,marks:8,topics:["8d"],difficulty:"Hard",summary:"Big Bang evidence, red-shift and calculating the observed wavelength of light from galaxies." },

  // May/June 2025 regional Paper 1PR
  { id:"phys-2025-mj-1PR-1",year:2025,session:"May/June",paper:"1PR",questionNumber:1,marks:5,topics:["1b","1c"],difficulty:"Easy",summary:"Resultant force, thinking distance, braking distance and stopping-distance factors." },
  { id:"phys-2025-mj-1PR-2",year:2025,session:"May/June",paper:"1PR",questionNumber:2,marks:7,topics:["6b"],difficulty:"Medium",summary:"Uniform magnetic fields, induced magnetism and permanent versus temporary magnets." },
  { id:"phys-2025-mj-1PR-3",year:2025,session:"May/June",paper:"1PR",questionNumber:3,marks:12,topics:["2c"],difficulty:"Hard",summary:"Circuit components, thermistors, resistance and current, including series resistance." },
  { id:"phys-2025-mj-1PR-4",year:2025,session:"May/June",paper:"1PR",questionNumber:4,marks:13,topics:["4b"],difficulty:"Hard",summary:"Investigating thermal conduction in metals, control variables, graphing and interpreting results." },
  { id:"phys-2025-mj-1PR-5",year:2025,session:"May/June",paper:"1PR",questionNumber:5,marks:10,topics:["7b"],difficulty:"Medium",summary:"Alpha radiation, nuclear equations, safety and interpreting cloud-chamber tracks." },
  { id:"phys-2025-mj-1PR-6",year:2025,session:"May/June",paper:"1PR",questionNumber:6,marks:10,topics:["1b"],difficulty:"Medium",summary:"Rocket motion using acceleration, distance equations and velocity-time and distance-time graphs." },
  { id:"phys-2025-mj-1PR-7",year:2025,session:"May/June",paper:"1PR",questionNumber:7,marks:11,topics:["3b","3d"],difficulty:"Hard",summary:"Transverse light waves, reflection, total internal reflection and refractive index." },
  { id:"phys-2025-mj-1PR-8",year:2025,session:"May/June",paper:"1PR",questionNumber:8,marks:7,topics:["8b"],difficulty:"Medium",summary:"The Solar System, orbital paths, orbital speed and comparing orbital periods." },
  { id:"phys-2025-mj-1PR-9",year:2025,session:"May/June",paper:"1PR",questionNumber:9,marks:14,topics:["4b","6d"],difficulty:"Hard",summary:"Energy stores in springs and electromagnetic induction in regenerative shock absorbers." },
  { id:"phys-2025-mj-1PR-10",year:2025,session:"May/June",paper:"1PR",questionNumber:10,marks:11,topics:["5b"],difficulty:"Medium",summary:"Measuring mass and volume of a gold ring, density, anomalies and displacement accuracy." },
  { id:"phys-2025-mj-1PR-11",year:2025,session:"May/June",paper:"1PR",questionNumber:11,marks:10,topics:["4b","3b"],difficulty:"Hard",summary:"Kinetic energy and the Doppler effect for reflected radio waves." },

  // May/June 2025 regional Paper 2PR
  { id:"phys-2025-mj-2PR-1",year:2025,session:"May/June",paper:"2PR",questionNumber:1,marks:6,topics:["2d"],difficulty:"Medium",summary:"Charging by friction, electrostatic forces and earthing in a flour mill." },
  { id:"phys-2025-mj-2PR-2",year:2025,session:"May/June",paper:"2PR",questionNumber:2,marks:7,topics:["7b"],difficulty:"Medium",summary:"Isotopes, nuclear particles, beta decay and half-life." },
  { id:"phys-2025-mj-2PR-3",year:2025,session:"May/June",paper:"2PR",questionNumber:3,marks:9,topics:["4d","4b","4c"],difficulty:"Medium",summary:"Tidal power advantages and disadvantages, gravitational energy and power." },
  { id:"phys-2025-mj-2PR-4",year:2025,session:"May/June",paper:"2PR",questionNumber:4,marks:7,topics:["6d"],difficulty:"Medium",summary:"Step-up transformer structure, power and output voltage." },
  { id:"phys-2025-mj-2PR-5",year:2025,session:"May/June",paper:"2PR",questionNumber:5,marks:15,topics:["1c","1b"],difficulty:"Hard",summary:"Forces and momentum in a bouncing ball, then designing a coefficient-of-restitution investigation." },
  { id:"phys-2025-mj-2PR-6",year:2025,session:"May/June",paper:"2PR",questionNumber:6,marks:10,topics:["8d","3b"],difficulty:"Hard",summary:"Cosmic microwave background radiation, wavelength and red-shift evidence for the Big Bang." },
  { id:"phys-2025-mj-2PR-7",year:2025,session:"May/June",paper:"2PR",questionNumber:7,marks:10,topics:["4b"],difficulty:"Medium",summary:"Thermal radiation and insulation, then cooling curves and rates of temperature change." },
  { id:"phys-2025-mj-2PR-8",year:2025,session:"May/June",paper:"2PR",questionNumber:8,marks:6,topics:["3d"],difficulty:"Medium",summary:"Human hearing, sound frequency and oscilloscope settings." },

  // May/June 2026 Paper 1P
  { id:"phys-2026-mj-1P-1",year:2026,session:"May/June",paper:"1P",questionNumber:1,marks:8,topics:["8c","7c"],difficulty:"Medium",summary:"Stellar evolution and the process and required conditions of nuclear fusion." },
  { id:"phys-2026-mj-1P-2",year:2026,session:"May/June",paper:"1P",questionNumber:2,marks:12,topics:["5b","5d"],difficulty:"Hard",summary:"Atmospheric pressure, gas temperature and pressure, and molecular kinetic energy on Venus." },
  { id:"phys-2026-mj-1P-3",year:2026,session:"May/June",paper:"1P",questionNumber:3,marks:6,topics:["8b"],difficulty:"Medium",summary:"Elliptical orbits, gravitational force, orbital speed and gravitational field strength." },
  { id:"phys-2026-mj-1P-4",year:2026,session:"May/June",paper:"1P",questionNumber:4,marks:13,topics:["1c"],difficulty:"Hard",summary:"Investigating force and extension in a metal wire, variables, safety and the elastic limit." },
  { id:"phys-2026-mj-1P-5",year:2026,session:"May/June",paper:"1P",questionNumber:5,marks:13,topics:["2c","3d"],difficulty:"Hard",summary:"Parallel street lamps, reflection, refraction, refractive index and total internal reflection." },
  { id:"phys-2026-mj-1P-6",year:2026,session:"May/June",paper:"1P",questionNumber:6,marks:7,topics:["3c","4b"],difficulty:"Medium",summary:"Electromagnetic waves in ovens, microwave frequency and heat transfer through food." },
  { id:"phys-2026-mj-1P-7",year:2026,session:"May/June",paper:"1P",questionNumber:7,marks:12,topics:["7c","7b"],difficulty:"Hard",summary:"Thorium and uranium nuclear equations, fission chain reactions and radioactive half-life." },
  { id:"phys-2026-mj-1P-8",year:2026,session:"May/June",paper:"1P",questionNumber:8,marks:8,topics:["6c","6d"],difficulty:"Medium",summary:"Alternating current, loudspeaker operation and electromagnetic induction in a microphone." },
  { id:"phys-2026-mj-1P-9",year:2026,session:"May/June",paper:"1P",questionNumber:9,marks:12,topics:["1b"],difficulty:"Hard",summary:"Light-gate measurements, acceleration, graphing speed squared against distance and gradients." },
  { id:"phys-2026-mj-1P-10",year:2026,session:"May/June",paper:"1P",questionNumber:10,marks:12,topics:["2c"],difficulty:"Hard",summary:"LDR circuits, voltmeter placement, resistance calculations and doubling current." },
  { id:"phys-2026-mj-1P-11",year:2026,session:"May/June",paper:"1P",questionNumber:11,marks:7,topics:["4c","1c"],difficulty:"Medium",summary:"Kinetic energy, work done by braking forces and the effect of speed on braking distance." },

  // May/June 2026 regional Paper 1PR
  { id:"phys-2026-mj-1PR-1",year:2026,session:"May/June",paper:"1PR",questionNumber:1,marks:6,topics:["8b","8c"],difficulty:"Medium",summary:"Solar System objects and the future evolution of the Sun." },
  { id:"phys-2026-mj-1PR-2",year:2026,session:"May/June",paper:"1PR",questionNumber:2,marks:6,topics:["6b"],difficulty:"Medium",summary:"Magnetic field diagrams, field direction and permanent magnetism in steel." },
  { id:"phys-2026-mj-1PR-3",year:2026,session:"May/June",paper:"1PR",questionNumber:3,marks:10,topics:["2b","4b","4c"],difficulty:"Medium",summary:"Alternating current, electrical power and reducing heat loss from a water bath." },
  { id:"phys-2026-mj-1PR-4",year:2026,session:"May/June",paper:"1PR",questionNumber:4,marks:9,topics:["3b","3c"],difficulty:"Medium",summary:"Microwave amplitude, wavelength, frequency, distance and reflection from metal." },
  { id:"phys-2026-mj-1PR-5",year:2026,session:"May/June",paper:"1PR",questionNumber:5,marks:14,topics:["2c"],difficulty:"Hard",summary:"Electric current, series resistance and an investigation of current against resistor number." },
  { id:"phys-2026-mj-1PR-6",year:2026,session:"May/June",paper:"1PR",questionNumber:6,marks:7,topics:["7c"],difficulty:"Medium",summary:"The process of nuclear fusion and the temperature and pressure conditions required." },
  { id:"phys-2026-mj-1PR-7",year:2026,session:"May/June",paper:"1PR",questionNumber:7,marks:11,topics:["5b"],difficulty:"Hard",summary:"Determining the density of air by measuring displaced water and the mass of a balloon." },
  { id:"phys-2026-mj-1PR-8",year:2026,session:"May/June",paper:"1PR",questionNumber:8,marks:12,topics:["5d"],difficulty:"Hard",summary:"Absolute zero, gas pressure and volume, and pressure changes at constant volume." },
  { id:"phys-2026-mj-1PR-9",year:2026,session:"May/June",paper:"1PR",questionNumber:9,marks:8,topics:["3d"],difficulty:"Medium",summary:"Refraction through a prism, refractive index, dispersion and graph interpretation." },
  { id:"phys-2026-mj-1PR-10",year:2026,session:"May/June",paper:"1PR",questionNumber:10,marks:13,topics:["7b","1b"],difficulty:"Hard",summary:"Beta particles, nuclear equations, ionisation and acceleration through aluminium." },
  { id:"phys-2026-mj-1PR-11",year:2026,session:"May/June",paper:"1PR",questionNumber:11,marks:14,topics:["1b","1c"],difficulty:"Hard",summary:"Skydiving weight, resultant force, acceleration and distance from a velocity-time graph." },

  // May/June 2026 Paper 2P
  { id:"phys-2026-mj-2P-1",year:2026,session:"May/June",paper:"2P",questionNumber:1,marks:8,topics:["5c","4b"],difficulty:"Medium",summary:"A specific heat capacity investigation, electrical energy and calculation of specific heat capacity." },
  { id:"phys-2026-mj-2P-2",year:2026,session:"May/June",paper:"2P",questionNumber:2,marks:9,topics:["1c"],difficulty:"Medium",summary:"Moments in equilibrium and how support forces change as a person crosses a beam." },
  { id:"phys-2026-mj-2P-3",year:2026,session:"May/June",paper:"2P",questionNumber:3,marks:9,topics:["6b","6c"],difficulty:"Medium",summary:"Electromagnet construction, induced magnetism and magnetic field lines." },
  { id:"phys-2026-mj-2P-4",year:2026,session:"May/June",paper:"2P",questionNumber:4,marks:10,topics:["7c","4b","4d"],difficulty:"Medium",summary:"Energy transfers in a fission power station, radiation safety and efficiency." },
  { id:"phys-2026-mj-2P-5",year:2026,session:"May/June",paper:"2P",questionNumber:5,marks:7,topics:["2d"],difficulty:"Medium",summary:"Charging balloons by friction and testing the inverse-square electrostatic force relationship." },
  { id:"phys-2026-mj-2P-6",year:2026,session:"May/June",paper:"2P",questionNumber:6,marks:11,topics:["3d"],difficulty:"Hard",summary:"Human hearing, oscilloscope measurements, sound frequency and presenting animal data." },
  { id:"phys-2026-mj-2P-7",year:2026,session:"May/June",paper:"2P",questionNumber:7,marks:7,topics:["8d"],difficulty:"Medium",summary:"Red-shift evidence for the Big Bang and evaluating a star's recession speed." },
  { id:"phys-2026-mj-2P-8",year:2026,session:"May/June",paper:"2P",questionNumber:8,marks:9,topics:["3b","1c"],difficulty:"Medium",summary:"The Doppler effect in sound and radio signals, followed by momentum during spacecraft docking." },

  // May/June 2026 regional Paper 2PR
  { id:"phys-2026-mj-2PR-1",year:2026,session:"May/June",paper:"2PR",questionNumber:1,marks:5,topics:["8d"],difficulty:"Medium",summary:"Direct evidence for the Big Bang and how physical quantities changed as the universe expanded." },
  { id:"phys-2026-mj-2PR-2",year:2026,session:"May/June",paper:"2PR",questionNumber:2,marks:9,topics:["2d","2b"],difficulty:"Medium",summary:"Electrostatic air filtering, charging dust, attraction, insulation and earthing." },
  { id:"phys-2026-mj-2PR-3",year:2026,session:"May/June",paper:"2PR",questionNumber:3,marks:10,topics:["4d","7c"],difficulty:"Medium",summary:"Fuel energy density, renewable wood and the products and disadvantages of nuclear fission." },
  { id:"phys-2026-mj-2PR-4",year:2026,session:"May/June",paper:"2PR",questionNumber:4,marks:14,topics:["1c"],difficulty:"Hard",summary:"Measuring pool-ball speed and contact time, then calculating momentum and force." },
  { id:"phys-2026-mj-2PR-5",year:2026,session:"May/June",paper:"2PR",questionNumber:5,marks:9,topics:["5c"],difficulty:"Medium",summary:"Particle changes during melting and calculating the mass of heated liquid gallium." },
  { id:"phys-2026-mj-2PR-6",year:2026,session:"May/June",paper:"2PR",questionNumber:6,marks:8,topics:["7b"],difficulty:"Medium",summary:"Becquerel's discovery of radioactivity and identifying radiation in a magnetic field." },
  { id:"phys-2026-mj-2PR-7",year:2026,session:"May/June",paper:"2PR",questionNumber:7,marks:6,topics:["1c"],difficulty:"Medium",summary:"Moments of a uniform bar and calculating the upward forces at two supports." },
  { id:"phys-2026-mj-2PR-8",year:2026,session:"May/June",paper:"2PR",questionNumber:8,marks:9,topics:["6d","3d"],difficulty:"Medium",summary:"Microphone electromagnetic induction, damage from loud sounds and measuring frequency." },

];
