import type { Question } from "./questions";

// Metadata transcribed from the uploaded January 2012 and January 2013
// Higher-tier Word question papers. Both the generator and question bank
// consume these entries through the shared questionBank.ts array.
type QuestionData = [number, string, string];
function makePaper(year: number, paper: string, entries: QuestionData[]): Question[] {
  return entries.map(([marks, topicList, summary], i) => ({
    id: `${year}-jan-${paper}-${i + 1}`,
    year,
    session: "January",
    paper,
    questionNumber: i + 1,
    marks,
    topics: topicList.split("|"),
    difficulty: marks <= 3 ? "Easy" : marks >= 7 ? "Hard" : "Medium",
    summary,
  }));
}

export const questions_2012_2013: Question[] = [
  ...makePaper(2012, "3H", [[5,"Percentages","Population percentages and percentage increase."],[2,"Probability","Estimate spinner colour frequency."],[3,"Surface Area and Volume","Calculate cylinder volume."],[4,"Constructions","Construct a rhombus accurately."],[7,"Algebra|Factorising|Expanding","Factorise, expand and substitute into a formula."],[4,"Sets","Set notation and operations with students and numbers."],[6,"Statistics|Grouped Data|Estimated Mean","Modal class and estimated mean of grouped texts."],[6,"Probability|Algebra|Linear Equations","Bead probabilities and solving an equation."],[5,"Trigonometry|Bounds","Right-angle trigonometry and bounds on a length."],[3,"Percentages|Compound Interest","Calculate compound interest over three years."],[3,"Algebra|Linear Equations","Rearrange an algebraic equation to make y the subject."],[7,"Similarity|Area and Perimeter","Similar quadrilaterals, scale factors and area."],[4,"Circle Theorems|Angles","Angles in a circle and angle reasoning."],[8,"Differentiation|Quadratics|Area and Perimeter","Rectangle area function and its maximum."],[6,"Proportion","Inverse-square force and distance proportionality."],[6,"Histograms|Grouped Data|Statistics","Frequency table and histogram of race times."],[2,"Fractions","Prove a recurring decimal equals a fraction."],[6,"Area and Perimeter|Circle Theorems","Find the area of a circular segment."],[3,"Indices|Surds","Simplify an expression into a required exact form."],[3,"Algebraic Fractions|Algebra","Simplify an algebraic expression fully."],[7,"Quadratics|Area and Perimeter","Trapezium area, quadratic equation and perimeter."]]),
  ...makePaper(2012, "4H", [[2,"Number","Evaluate a numerical expression as a decimal."],[3,"Speed","Find flight time from speed and distance."],[3,"Linear Equations","Solve a linear equation."],[3,"Statistics","Find range using the median and mean."],[4,"Graphs","Draw a straight-line graph on a grid."],[5,"Ratio|Similarity","Student ratio and lorry scale-model lengths."],[3,"HCF and LCM|Indices","Prime factor decomposition of 200."],[2,"Indices","Solve an equation involving powers."],[6,"Area and Perimeter|Trigonometry","Area of a rhombus and side length."],[4,"Inequalities","Solve inequalities and list possible integer values."],[4,"HCF and LCM","Calculate HCF and LCM of two integers."],[6,"Transformations","Describe transformations and translate a triangle."],[8,"Coordinate Geometry|Simultaneous Equations","Gradient and intersection of two straight lines."],[5,"Cumulative Frequency|Statistics","Complete a cumulative-frequency table and graph."],[2,"Inequalities|Quadratics","Solve a quadratic inequality."],[7,"Probability","Probability with dominoes drawn without replacement."],[12,"Functions|Graphs","Composite functions, domains and graph readings."],[3,"Trigonometry","Calculate a missing length in a diagram."],[4,"Sets","Complete and interpret a two-set Venn diagram."],[5,"Surface Area and Volume","Calculate cone volume from curved surface area."],[4,"Algebra|Indices","Simplify expressions and rearrange an equation."],[5,"Vectors","Vector calculations and geometric proof."]]),
  ...makePaper(2013, "3H", [[4,"Probability","Biased spinner probability and expected frequency."],[4,"Area and Perimeter|Linear Equations","Compare perimeters of two rectangles to solve for x."],[11,"Percentages|Speed","Travel costs, pay increases and average speed."],[5,"Transformations","Enlargement and rotation on a coordinate grid."],[3,"Simultaneous Equations","Solve a pair of simultaneous equations."],[4,"Statistics|Grouped Data|Estimated Mean","Modal class and estimated total of grouped journey distances."],[4,"Inequalities","Solve and represent inequalities on a number line."],[5,"Trigonometry|Bounds","Right-angled triangle calculation and angle bounds."],[5,"Standard Form|Number","Planet diameters and standard-form calculations."],[5,"Coordinate Geometry|Graphs","Gradient, equation and parallel straight lines."],[4,"Trigonometry","Calculate the length of a washing line."],[2,"Algebra","Rearrange a formula to make h the subject."],[4,"Histograms|Grouped Data","Complete a frequency table and histogram."],[6,"Probability","Complete a probability tree for two arrows."],[4,"Sets","Read a three-set Venn diagram."],[3,"Trigonometry","Calculate x using a geometric diagram."],[3,"Algebraic Fractions|Algebra","Simplify an algebraic expression fully."],[7,"Differentiation|Quadratics","Differentiate a curve and find its turning point."],[8,"Quadratics|Area and Perimeter","Use playground dimensions to form and solve a quadratic."],[5,"Vectors","Vector expressions and a collinearity proof."],[4,"Trigonometry|Surface Area and Volume","Find angle between an edge and the base of a pyramid."]]),
  ...makePaper(2013, "4H", [[3,"Number","Evaluate a calculator expression and round to significant figures."],[2,"Circle Theorems|Area and Perimeter","Calculate circumference from circle diameter."],[3,"Statistics|Grouped Data","Find the mean from a frequency table."],[2,"Probability","Probability of a bus arriving early or on time."],[3,"Sets","List members of sets using intersections."],[5,"Fractions","Fractions of a group and minimum possible group size."],[4,"Area and Perimeter","Calculate the area of a compound shape."],[6,"Algebra|Factorising|Expanding","Factorise and expand algebraic expressions."],[3,"Pythagoras","Use Pythagoras to find a triangle length."],[3,"Linear Equations","Solve a linear equation."],[3,"Ratio","Share money in a given ratio."],[2,"Constructions","Construct an angle bisector using ruler and compasses."],[3,"Inequalities|Graphs","Write inequalities for a shaded region."],[4,"Algebraic Fractions|Linear Equations","Solve an equation involving fractions."],[4,"Algebraic Fractions|Algebra","Simplify two algebraic expressions."],[5,"Cumulative Frequency|Statistics","Complete cumulative-frequency table and draw graph."],[7,"Similarity|Area and Perimeter","Similar triangles and areas."],[3,"Quadratics","Solve a quadratic equation to three significant figures."],[3,"Indices|Surds","Find integers from an expression in index form."],[5,"Probability","Two-stage probability using discs in two boxes."],[5,"Proportion","Direct-square proportionality of exposure time."],[4,"Circle Theorems|Angles","Find angle between two tangents to a circle."],[3,"Functions","Evaluate a function and a composite function."],[3,"Percentages|Speed","Percentage reduction in journey time."],[6,"Trigonometry","Use angles of elevation to calculate a flagpole height."],[6,"Simultaneous Equations|Quadratics","Solve simultaneous linear and quadratic equations."]]),
];
