import type { Question } from "./questions";

export const questions_2025_may_1h: Question[] = [
  { id:"2025-may-1H-1",year:2025,session:"May",paper:"1H",questionNumber:1,marks:5,topics:["Grouped Data","Statistics"],difficulty:"Medium",summary:"Use a grouped frequency table to identify the modal class and estimate the mean distance." },
  { id:"2025-may-1H-2",year:2025,session:"May",paper:"1H",questionNumber:2,marks:6,topics:["Percentages","Bounds"],difficulty:"Hard",summary:"Calculate percentage profit, then identify lower and upper bounds for rounded measurements." },
  { id:"2025-may-1H-3",year:2025,session:"May",paper:"1H",questionNumber:3,marks:4,topics:["Angles","Polygons"],difficulty:"Medium",summary:"Use angle facts to find the number of sides of a regular polygon." },
  { id:"2025-may-1H-4",year:2025,session:"May",paper:"1H",questionNumber:4,marks:4,topics:["Indices","Algebra"],difficulty:"Medium",summary:"Apply index laws and simplify a power expression." },
  { id:"2025-may-1H-5",year:2025,session:"May",paper:"1H",questionNumber:5,marks:3,topics:["Percentages","Reverse Percentages"],difficulty:"Medium",summary:"Find the original price from a 28% sale reduction." },
  { id:"2025-may-1H-6",year:2025,session:"May",paper:"1H",questionNumber:6,marks:6,topics:["Linear Equations","Quadratics","Factorising"],difficulty:"Hard",summary:"Solve a linear equation, factorise a quadratic and hence solve it." },
  { id:"2025-may-1H-7",year:2025,session:"May",paper:"1H",questionNumber:7,marks:3,topics:["Surface Area and Volume"],difficulty:"Medium",summary:"Find the height of a cylinder from its radius and volume." },
  { id:"2025-may-1H-8",year:2025,session:"May",paper:"1H",questionNumber:8,marks:4,topics:["Standard Form"],difficulty:"Medium",summary:"Convert numbers to and from standard form and calculate with powers of ten." },
  { id:"2025-may-1H-9",year:2025,session:"May",paper:"1H",questionNumber:9,marks:5,topics:["Area and Perimeter","Trigonometry"],difficulty:"Medium",summary:"Find the area of a symmetric trapezium using trigonometry." },
  { id:"2025-may-1H-10",year:2025,session:"May",paper:"1H",questionNumber:10,marks:3,topics:["Graphs"],difficulty:"Medium",summary:"Complete a table and draw a cubic graph." },
  { id:"2025-may-1H-11",year:2025,session:"May",paper:"1H",questionNumber:11,marks:2,topics:["Area and Perimeter","Angles"],difficulty:"Easy",summary:"Calculate the area of a sector." },
  { id:"2025-may-1H-12",year:2025,session:"May",paper:"1H",questionNumber:12,marks:3,topics:["Algebraic Fractions"],difficulty:"Medium",summary:"Express algebraic fractions as a single simplified fraction." },
  { id:"2025-may-1H-13",year:2025,session:"May",paper:"1H",questionNumber:13,marks:3,topics:["Percentages","Compound Growth"],difficulty:"Medium",summary:"Calculate successive percentage changes in the value of an apartment." },
  { id:"2025-may-1H-14",year:2025,session:"May",paper:"1H",questionNumber:14,marks:4,topics:["Probability"],difficulty:"Medium",summary:"Calculate combined probabilities for badminton and tennis results." },
  { id:"2025-may-1H-15",year:2025,session:"May",paper:"1H",questionNumber:15,marks:4,topics:["Surds","Proof"],difficulty:"Medium",summary:"Find an integer and show a surd expression can be written in a required form." },
  { id:"2025-may-1H-16",year:2025,session:"May",paper:"1H",questionNumber:16,marks:4,topics:["Functions","Quadratics"],difficulty:"Medium",summary:"Evaluate a function and solve an inequality involving a composite function." },
  { id:"2025-may-1H-17",year:2025,session:"May",paper:"1H",questionNumber:17,marks:3,topics:["Histograms","Statistics"],difficulty:"Medium",summary:"Use a histogram to estimate a proportion of people in a time interval." },
  { id:"2025-may-1H-18",year:2025,session:"May",paper:"1H",questionNumber:18,marks:4,topics:["Proportion","Algebra"],difficulty:"Medium",summary:"Use inverse proportion with y proportional to 1/x³." },
  { id:"2025-may-1H-19",year:2025,session:"May",paper:"1H",questionNumber:19,marks:2,topics:["Functions","Transformations"],difficulty:"Easy",summary:"Track the minimum point of a transformed function graph." },
  { id:"2025-may-1H-20",year:2025,session:"May",paper:"1H",questionNumber:20,marks:5,topics:["Trigonometry"],difficulty:"Medium",summary:"Use a geometry diagram to calculate the length BC to 3 significant figures." },
  { id:"2025-may-1H-21",year:2025,session:"May",paper:"1H",questionNumber:21,marks:3,topics:["Probability"],difficulty:"Medium",summary:"Calculate probability using counters of three colours." },
  { id:"2025-may-1H-22",year:2025,session:"May",paper:"1H",questionNumber:22,marks:5,topics:["Simultaneous Equations","Quadratics"],difficulty:"Medium",summary:"Solve simultaneous equations containing a quadratic relation." },
  { id:"2025-may-1H-23",year:2025,session:"May",paper:"1H",questionNumber:23,marks:5,topics:["Vectors"],difficulty:"Medium",summary:"Use vectors in a triangle with midpoint and intersection points." },
  { id:"2025-may-1H-24",year:2025,session:"May",paper:"1H",questionNumber:24,marks:5,topics:["Arithmetic Sequences"],difficulty:"Medium",summary:"Use terms and sums of a 30-term arithmetic series." },
  { id:"2025-may-1H-25",year:2025,session:"May",paper:"1H",questionNumber:25,marks:5,topics:["Coordinate Geometry","Graphs"],difficulty:"Medium",summary:"Use coordinates of opposite vertices of a square to determine missing information." },
];