import type { Question } from "./questions";

export const questions_2025_june_2h: Question[] = [
  { id:"2025-june-2H-1",year:2025,session:"June",paper:"2H",questionNumber:1,marks:3,topics:["Statistics"],difficulty:"Medium",summary:"Rio has six cards. He writes a number on each card so that the range of the numbers is 10 the median of the numbers is 7.5" },
  { id:"2025-june-2H-2",year:2025,session:"June",paper:"2H",questionNumber:2,marks:5,topics:["Transformations", "Trigonometry", "Graphs"],difficulty:"Medium",summary:"(a) On the grid, enlarge shape A with scale factor 3 and centre (0, 1) (b) Describe fully the single transformation that maps triangle P onto triangle Q." },
  { id:"2025-june-2H-3",year:2025,session:"June",paper:"2H",questionNumber:3,marks:3,topics:["Proof"],difficulty:"Medium",summary:"Show that the given mixed-number subtraction is correct." },
  { id:"2025-june-2H-4",year:2025,session:"June",paper:"2H",questionNumber:4,marks:2,topics:["Constructions"],difficulty:"Easy",summary:"Construct the perpendicular bisector of line AB using ruler and compasses." },
  { id:"2025-june-2H-5",year:2025,session:"June",paper:"2H",questionNumber:5,marks:4,topics:["Similar Shapes"],difficulty:"Medium",summary:"Use similar quadrilaterals to find missing side lengths x and y." },
  { id:"2025-june-2H-6",year:2025,session:"June",paper:"2H",questionNumber:6,marks:4,topics:["Ratio"],difficulty:"Medium",summary:"Share money in a ratio, transfer amounts, then simplify the new ratio." },
  { id:"2025-june-2H-7",year:2025,session:"June",paper:"2H",questionNumber:7,marks:3,topics:["Compound Interest","Percentages"],difficulty:"Medium",summary:"Calculate the value of a bracelet after 3 years of 7% annual growth." },
  { id:"2025-june-2H-8",year:2025,session:"June",paper:"2H",questionNumber:8,marks:3,topics:["Simultaneous Equations"],difficulty:"Medium",summary:"Solve a pair of linear simultaneous equations algebraically." },
  { id:"2025-june-2H-9",year:2025,session:"June",paper:"2H",questionNumber:9,marks:5,topics:["Inequalities","Graphs"],difficulty:"Medium",summary:"Solve a linear inequality and write inequalities defining a shaded region." },
  { id:"2025-june-2H-10",year:2025,session:"June",paper:"2H",questionNumber:10,marks:5,topics:["Trigonometry"],difficulty:"Medium",summary:"Use two right-angled triangles to find CD to 3 significant figures." },
  { id:"2025-june-2H-11",year:2025,session:"June",paper:"2H",questionNumber:11,marks:3,topics:["Probability"],difficulty:"Medium",summary:"Find the number of orange counters from a given probability." },
  { id:"2025-june-2H-12",year:2025,session:"June",paper:"2H",questionNumber:12,marks:3,topics:["Expanding","Algebra"],difficulty:"Medium",summary:"Expand and simplify 3x(2x + 5)(7x - 4)." },
  { id:"2025-june-2H-13",year:2025,session:"June",paper:"2H",questionNumber:13,marks:6,topics:["Cumulative Frequency","Grouped Data","Statistics"],difficulty:"Hard",summary:"Complete a cumulative frequency table and use cumulative frequency information." },
  { id:"2025-june-2H-14",year:2025,session:"June",paper:"2H",questionNumber:14,marks:2,topics:["Graphs","Functions"],difficulty:"Easy",summary:"Identify graphs that match given equations." },
  { id:"2025-june-2H-15",year:2025,session:"June",paper:"2H",questionNumber:15,marks:3,topics:["Algebra"],difficulty:"Medium",summary:"Simplify an algebraic expression fully." },
  { id:"2025-june-2H-16",year:2025,session:"June",paper:"2H",questionNumber:16,marks:4,topics:["Algebra","Changing the Subject"],difficulty:"Medium",summary:"Make t the subject of a formula." },
  { id:"2025-june-2H-17",year:2025,session:"June",paper:"2H",questionNumber:17,marks:6,topics:["Differentiation","Graphs"],difficulty:"Hard",summary:"Differentiate a cubic and find coordinates of its turning points." },
  { id:"2025-june-2H-18",year:2025,session:"June",paper:"2H",questionNumber:18,marks:2,topics:["Proof","Algebra"],difficulty:"Easy",summary:"Use algebra to prove the given result." },
  { id:"2025-june-2H-19",year:2025,session:"June",paper:"2H",questionNumber:19,marks:3,topics:["Quadratics","Inequalities"],difficulty:"Medium",summary:"Solve the quadratic inequality 4x² + 4x - 15 < 0." },
  { id:"2025-june-2H-20",year:2025,session:"June",paper:"2H",questionNumber:20,marks:6,topics:["Sets","Probability"],difficulty:"Hard",summary:"Use information about three overlapping sets of gardeners." },
  { id:"2025-june-2H-21",year:2025,session:"June",paper:"2H",questionNumber:21,marks:3,topics:["Surface Area and Volume","Algebra"],difficulty:"Medium",summary:"Use the volume and surface area of an algebraic cuboid." },
  { id:"2025-june-2H-22",year:2025,session:"June",paper:"2H",questionNumber:22,marks:4,topics:["Bounds","Area and Perimeter"],difficulty:"Medium",summary:"Use bounds with the shaded area of a square inside a rectangle." },
  { id:"2025-june-2H-23",year:2025,session:"June",paper:"2H",questionNumber:23,marks:4,topics:["Indices","Algebra"],difficulty:"Medium",summary:"Find an integer exponent p using index laws." },
  { id:"2025-june-2H-24",year:2025,session:"June",paper:"2H",questionNumber:24,marks:4,topics:["Trigonometry","3D Geometry"],difficulty:"Medium",summary:"Use geometry in a square-based pyramid with a midpoint on the base." },
  { id:"2025-june-2H-25",year:2025,session:"June",paper:"2H",questionNumber:25,marks:6,topics:["Quadratics","Graphs","Completing the Square"],difficulty:"Hard",summary:"Complete the square and sketch the resulting quadratic graph." },
  { id:"2025-june-2H-26",year:2025,session:"June",paper:"2H",questionNumber:26,marks:4,topics:["Similar Shapes","Surface Area and Volume"],difficulty:"Medium",summary:"Use scale factors between two similar solids." },
];