import type { Question } from "./questions";

// Questions shared by the Maths question bank, generator and swap selector.
export const questions_2012_2013_january: Question[] = [
  { id:"2012-jan-3H-1", year:2012, session:"January", paper:"3H", questionNumber:1, marks:5, topics:["Percentages"], difficulty:"Easy", summary:"Population percentage and percentage increase" },
  { id:"2012-jan-3H-2", year:2012, session:"January", paper:"3H", questionNumber:2, marks:2, topics:["Probability"], difficulty:"Easy", summary:"Estimate spinner outcomes" },
  { id:"2012-jan-3H-3", year:2012, session:"January", paper:"3H", questionNumber:3, marks:3, topics:["Surface Area and Volume"], difficulty:"Easy", summary:"Cylinder volume" },
  { id:"2012-jan-3H-4", year:2012, session:"January", paper:"3H", questionNumber:4, marks:4, topics:["Constructions"], difficulty:"Easy", summary:"Construct a rhombus" },
  { id:"2012-jan-3H-5", year:2012, session:"January", paper:"3H", questionNumber:5, marks:7, topics:["Algebra","Factorising","Expanding"], difficulty:"Medium", summary:"Factorise expand and substitute" },
  { id:"2012-jan-3H-6", year:2012, session:"January", paper:"3H", questionNumber:6, marks:4, topics:["Sets"], difficulty:"Medium", summary:"Interpret sets of language students" },
  { id:"2012-jan-3H-7", year:2012, session:"January", paper:"3H", questionNumber:7, marks:6, topics:["Grouped Data","Statistics","Estimated Mean"], difficulty:"Medium", summary:"Grouped modal class and estimated mean" },
  { id:"2012-jan-3H-8", year:2012, session:"January", paper:"3H", questionNumber:8, marks:6, topics:["Probability","Algebra"], difficulty:"Medium", summary:"Changing probabilities of coloured beads" },
  { id:"2012-jan-3H-9", year:2012, session:"January", paper:"3H", questionNumber:9, marks:5, topics:["Trigonometry","Bounds"], difficulty:"Medium", summary:"Right triangle and length bounds" },
  { id:"2012-jan-3H-10", year:2012, session:"January", paper:"3H", questionNumber:10, marks:3, topics:["Compound Interest","Percentages"], difficulty:"Medium", summary:"Compound interest on savings" },
  { id:"2012-jan-3H-11", year:2012, session:"January", paper:"3H", questionNumber:11, marks:3, topics:["Algebra"], difficulty:"Medium", summary:"Make y the subject" },
  { id:"2012-jan-3H-12", year:2012, session:"January", paper:"3H", questionNumber:12, marks:7, topics:["Similarity","Area and Perimeter"], difficulty:"Medium", summary:"Similar quadrilateral lengths and areas" },
  { id:"2012-jan-3H-13", year:2012, session:"January", paper:"3H", questionNumber:13, marks:4, topics:["Circle Theorems","Angles"], difficulty:"Medium", summary:"Circle theorem reasoning" },
  { id:"2012-jan-3H-14", year:2012, session:"January", paper:"3H", questionNumber:14, marks:8, topics:["Quadratics","Differentiation","Area and Perimeter"], difficulty:"Medium", summary:"Rectangular area and its maximum" },
  { id:"2012-jan-3H-15", year:2012, session:"January", paper:"3H", questionNumber:15, marks:6, topics:["Proportion"], difficulty:"Medium", summary:"Inverse square proportion" },
  { id:"2012-jan-3H-16", year:2012, session:"January", paper:"3H", questionNumber:16, marks:6, topics:["Histograms","Statistics"], difficulty:"Medium", summary:"Complete a histogram" },
  { id:"2012-jan-3H-17", year:2012, session:"January", paper:"3H", questionNumber:17, marks:2, topics:["Fractions"], difficulty:"Medium", summary:"Recurring decimal as a fraction" },
  { id:"2012-jan-3H-18", year:2012, session:"January", paper:"3H", questionNumber:18, marks:6, topics:["Area and Perimeter","Circle Theorems"], difficulty:"Hard", summary:"Circular segment area" },
  { id:"2012-jan-3H-19", year:2012, session:"January", paper:"3H", questionNumber:19, marks:3, topics:["Surds"], difficulty:"Hard", summary:"Expression in surd form" },
  { id:"2012-jan-3H-20", year:2012, session:"January", paper:"3H", questionNumber:20, marks:3, topics:["Algebraic Fractions"], difficulty:"Hard", summary:"Simplify an algebraic expression" },
  { id:"2012-jan-3H-21", year:2012, session:"January", paper:"3H", questionNumber:21, marks:7, topics:["Quadratics","Area and Perimeter"], difficulty:"Hard", summary:"Trapezium area quadratic and perimeter" },
  { id:"2012-jan-4H-1", year:2012, session:"January", paper:"4H", questionNumber:1, marks:2, topics:["Number"], difficulty:"Easy", summary:"Evaluate a numerical expression" },
  { id:"2012-jan-4H-2", year:2012, session:"January", paper:"4H", questionNumber:2, marks:3, topics:["Speed"], difficulty:"Easy", summary:"Time from flight distance and speed" },
  { id:"2012-jan-4H-3", year:2012, session:"January", paper:"4H", questionNumber:3, marks:3, topics:["Linear Equations"], difficulty:"Easy", summary:"Solve a linear equation" },
  { id:"2012-jan-4H-4", year:2012, session:"January", paper:"4H", questionNumber:4, marks:3, topics:["Statistics"], difficulty:"Easy", summary:"Range from mean and median" },
  { id:"2012-jan-4H-5", year:2012, session:"January", paper:"4H", questionNumber:5, marks:4, topics:["Graphs"], difficulty:"Medium", summary:"Straight line graph" },
  { id:"2012-jan-4H-6", year:2012, session:"January", paper:"4H", questionNumber:6, marks:5, topics:["Ratio","Similarity"], difficulty:"Medium", summary:"Student ratio and model scales" },
  { id:"2012-jan-4H-7", year:2012, session:"January", paper:"4H", questionNumber:7, marks:3, topics:["HCF and LCM","Indices"], difficulty:"Medium", summary:"Prime factors of 200" },
  { id:"2012-jan-4H-8", year:2012, session:"January", paper:"4H", questionNumber:8, marks:2, topics:["Indices"], difficulty:"Medium", summary:"Index laws and unknown exponent" },
  { id:"2012-jan-4H-9", year:2012, session:"January", paper:"4H", questionNumber:9, marks:6, topics:["Area and Perimeter","Trigonometry"], difficulty:"Medium", summary:"Rhombus area and side length" },
  { id:"2012-jan-4H-10", year:2012, session:"January", paper:"4H", questionNumber:10, marks:4, topics:["Inequalities"], difficulty:"Medium", summary:"Solve and list integer inequalities" },
  { id:"2012-jan-4H-11", year:2012, session:"January", paper:"4H", questionNumber:11, marks:4, topics:["HCF and LCM"], difficulty:"Medium", summary:"HCF and LCM calculations" },
  { id:"2012-jan-4H-12", year:2012, session:"January", paper:"4H", questionNumber:12, marks:6, topics:["Transformations"], difficulty:"Medium", summary:"Triangle transformations" },
  { id:"2012-jan-4H-13", year:2012, session:"January", paper:"4H", questionNumber:13, marks:8, topics:["Coordinate Geometry","Simultaneous Equations"], difficulty:"Medium", summary:"Gradient and intersecting lines" },
  { id:"2012-jan-4H-14", year:2012, session:"January", paper:"4H", questionNumber:14, marks:5, topics:["Cumulative Frequency","Statistics"], difficulty:"Medium", summary:"Cumulative frequency graph" },
  { id:"2012-jan-4H-15", year:2012, session:"January", paper:"4H", questionNumber:15, marks:2, topics:["Inequalities","Quadratics"], difficulty:"Medium", summary:"Quadratic inequality" },
  { id:"2012-jan-4H-16", year:2012, session:"January", paper:"4H", questionNumber:16, marks:7, topics:["Probability"], difficulty:"Medium", summary:"Dominoes without replacement" },
  { id:"2012-jan-4H-17", year:2012, session:"January", paper:"4H", questionNumber:17, marks:12, topics:["Functions","Graphs"], difficulty:"Medium", summary:"Functions domain and graph solutions" },
  { id:"2012-jan-4H-18", year:2012, session:"January", paper:"4H", questionNumber:18, marks:3, topics:["Trigonometry"], difficulty:"Medium", summary:"Trigonometry calculation" },
  { id:"2012-jan-4H-19", year:2012, session:"January", paper:"4H", questionNumber:19, marks:4, topics:["Sets"], difficulty:"Hard", summary:"Venn diagram and set calculations" },
  { id:"2012-jan-4H-20", year:2012, session:"January", paper:"4H", questionNumber:20, marks:5, topics:["Surface Area and Volume"], difficulty:"Hard", summary:"Cone volume from curved area" },
  { id:"2012-jan-4H-21", year:2012, session:"January", paper:"4H", questionNumber:21, marks:4, topics:["Algebra","Indices"], difficulty:"Hard", summary:"Expressions and formula rearrangement" },
  { id:"2012-jan-4H-22", year:2012, session:"January", paper:"4H", questionNumber:22, marks:5, topics:["Vectors","Proof"], difficulty:"Hard", summary:"Vector proof of collinear points" },
  { id:"2013-jan-3H-1", year:2013, session:"January", paper:"3H", questionNumber:1, marks:4, topics:["Probability"], difficulty:"Easy", summary:"Spinner probability and frequency" },
  { id:"2013-jan-3H-2", year:2013, session:"January", paper:"3H", questionNumber:2, marks:4, topics:["Linear Equations","Area and Perimeter"], difficulty:"Easy", summary:"Rectangle perimeter equation" },
  { id:"2013-jan-3H-3", year:2013, session:"January", paper:"3H", questionNumber:3, marks:11, topics:["Percentages","Speed"], difficulty:"Easy", summary:"Percentage changes and travel speed" },
  { id:"2013-jan-3H-4", year:2013, session:"January", paper:"3H", questionNumber:4, marks:5, topics:["Transformations"], difficulty:"Easy", summary:"Enlargement and rotation" },
  { id:"2013-jan-3H-5", year:2013, session:"January", paper:"3H", questionNumber:5, marks:3, topics:["Simultaneous Equations"], difficulty:"Medium", summary:"Solve simultaneous equations" },
  { id:"2013-jan-3H-6", year:2013, session:"January", paper:"3H", questionNumber:6, marks:4, topics:["Grouped Data","Statistics"], difficulty:"Medium", summary:"Grouped distances and modal class" },
  { id:"2013-jan-3H-7", year:2013, session:"January", paper:"3H", questionNumber:7, marks:4, topics:["Inequalities"], difficulty:"Medium", summary:"Solve and graph inequalities" },
  { id:"2013-jan-3H-8", year:2013, session:"January", paper:"3H", questionNumber:8, marks:5, topics:["Trigonometry","Bounds"], difficulty:"Medium", summary:"Triangle trigonometry and bounds" },
  { id:"2013-jan-3H-9", year:2013, session:"January", paper:"3H", questionNumber:9, marks:5, topics:["Standard Form"], difficulty:"Medium", summary:"Planet diameters in standard form" },
  { id:"2013-jan-3H-10", year:2013, session:"January", paper:"3H", questionNumber:10, marks:5, topics:["Coordinate Geometry","Graphs"], difficulty:"Medium", summary:"Parallel straight lines" },
  { id:"2013-jan-3H-11", year:2013, session:"January", paper:"3H", questionNumber:11, marks:4, topics:["Trigonometry"], difficulty:"Medium", summary:"Distance between different height posts" },
  { id:"2013-jan-3H-12", year:2013, session:"January", paper:"3H", questionNumber:12, marks:2, topics:["Algebra"], difficulty:"Medium", summary:"Make h the subject" },
  { id:"2013-jan-3H-13", year:2013, session:"January", paper:"3H", questionNumber:13, marks:4, topics:["Histograms","Statistics"], difficulty:"Medium", summary:"Complete a histogram" },
  { id:"2013-jan-3H-14", year:2013, session:"January", paper:"3H", questionNumber:14, marks:6, topics:["Probability"], difficulty:"Medium", summary:"Two shots at a target" },
  { id:"2013-jan-3H-15", year:2013, session:"January", paper:"3H", questionNumber:15, marks:4, topics:["Sets"], difficulty:"Medium", summary:"Three set Venn diagram" },
  { id:"2013-jan-3H-16", year:2013, session:"January", paper:"3H", questionNumber:16, marks:3, topics:["Trigonometry"], difficulty:"Medium", summary:"Trigonometry calculation" },
  { id:"2013-jan-3H-17", year:2013, session:"January", paper:"3H", questionNumber:17, marks:3, topics:["Algebraic Fractions"], difficulty:"Medium", summary:"Simplify fully" },
  { id:"2013-jan-3H-18", year:2013, session:"January", paper:"3H", questionNumber:18, marks:7, topics:["Differentiation","Quadratics"], difficulty:"Hard", summary:"Derivative and turning point" },
  { id:"2013-jan-3H-19", year:2013, session:"January", paper:"3H", questionNumber:19, marks:8, topics:["Quadratics","Area and Perimeter"], difficulty:"Hard", summary:"Playground area quadratic" },
  { id:"2013-jan-3H-20", year:2013, session:"January", paper:"3H", questionNumber:20, marks:5, topics:["Vectors","Proof"], difficulty:"Hard", summary:"Parallelogram vector proof" },
  { id:"2013-jan-3H-21", year:2013, session:"January", paper:"3H", questionNumber:21, marks:4, topics:["Trigonometry"], difficulty:"Hard", summary:"Angle to base of a pyramid" },
  { id:"2013-jan-4H-1", year:2013, session:"January", paper:"4H", questionNumber:1, marks:3, topics:["Number"], difficulty:"Easy", summary:"Calculator expression and significant figures" },
  { id:"2013-jan-4H-2", year:2013, session:"January", paper:"4H", questionNumber:2, marks:2, topics:["Area and Perimeter"], difficulty:"Easy", summary:"Circumference of a circle" },
  { id:"2013-jan-4H-3", year:2013, session:"January", paper:"4H", questionNumber:3, marks:3, topics:["Statistics"], difficulty:"Easy", summary:"Mean from a frequency table" },
  { id:"2013-jan-4H-4", year:2013, session:"January", paper:"4H", questionNumber:4, marks:2, topics:["Probability"], difficulty:"Easy", summary:"Bus arrival probability" },
  { id:"2013-jan-4H-5", year:2013, session:"January", paper:"4H", questionNumber:5, marks:3, topics:["Sets"], difficulty:"Medium", summary:"Sets and intersection conditions" },
  { id:"2013-jan-4H-6", year:2013, session:"January", paper:"4H", questionNumber:6, marks:5, topics:["Fractions","Probability"], difficulty:"Medium", summary:"Fraction of a group and minimum total" },
  { id:"2013-jan-4H-7", year:2013, session:"January", paper:"4H", questionNumber:7, marks:4, topics:["Area and Perimeter"], difficulty:"Medium", summary:"Compound shape area" },
  { id:"2013-jan-4H-8", year:2013, session:"January", paper:"4H", questionNumber:8, marks:6, topics:["Algebra","Factorising","Expanding"], difficulty:"Medium", summary:"Factorise expand and simplify" },
  { id:"2013-jan-4H-9", year:2013, session:"January", paper:"4H", questionNumber:9, marks:3, topics:["Pythagoras"], difficulty:"Medium", summary:"Right triangle missing side" },
  { id:"2013-jan-4H-10", year:2013, session:"January", paper:"4H", questionNumber:10, marks:3, topics:["Linear Equations"], difficulty:"Medium", summary:"Solve a linear equation" },
  { id:"2013-jan-4H-11", year:2013, session:"January", paper:"4H", questionNumber:11, marks:3, topics:["Ratio"], difficulty:"Medium", summary:"Money sharing ratio" },
  { id:"2013-jan-4H-12", year:2013, session:"January", paper:"4H", questionNumber:12, marks:2, topics:["Constructions"], difficulty:"Medium", summary:"Angle bisector construction" },
  { id:"2013-jan-4H-13", year:2013, session:"January", paper:"4H", questionNumber:13, marks:3, topics:["Inequalities","Graphs"], difficulty:"Medium", summary:"Inequalities of a shaded region" },
  { id:"2013-jan-4H-14", year:2013, session:"January", paper:"4H", questionNumber:14, marks:4, topics:["Linear Equations"], difficulty:"Medium", summary:"Solve an equation" },
  { id:"2013-jan-4H-15", year:2013, session:"January", paper:"4H", questionNumber:15, marks:4, topics:["Algebraic Fractions","Indices"], difficulty:"Medium", summary:"Simplify algebraic expressions" },
  { id:"2013-jan-4H-16", year:2013, session:"January", paper:"4H", questionNumber:16, marks:5, topics:["Cumulative Frequency","Statistics"], difficulty:"Medium", summary:"Cumulative frequency graph and median" },
  { id:"2013-jan-4H-17", year:2013, session:"January", paper:"4H", questionNumber:17, marks:7, topics:["Similarity","Area and Perimeter"], difficulty:"Medium", summary:"Similar triangles sides and areas" },
  { id:"2013-jan-4H-18", year:2013, session:"January", paper:"4H", questionNumber:18, marks:3, topics:["Quadratics"], difficulty:"Medium", summary:"Solve a quadratic" },
  { id:"2013-jan-4H-19", year:2013, session:"January", paper:"4H", questionNumber:19, marks:3, topics:["Surds","Indices"], difficulty:"Medium", summary:"Integer constants in an expression" },
  { id:"2013-jan-4H-20", year:2013, session:"January", paper:"4H", questionNumber:20, marks:5, topics:["Probability"], difficulty:"Medium", summary:"Discs transferred between boxes" },
  { id:"2013-jan-4H-21", year:2013, session:"January", paper:"4H", questionNumber:21, marks:5, topics:["Proportion"], difficulty:"Medium", summary:"Direct square proportion" },
  { id:"2013-jan-4H-22", year:2013, session:"January", paper:"4H", questionNumber:22, marks:4, topics:["Circle Theorems","Angles"], difficulty:"Medium", summary:"Angle between circle tangents" },
  { id:"2013-jan-4H-23", year:2013, session:"January", paper:"4H", questionNumber:23, marks:3, topics:["Functions"], difficulty:"Hard", summary:"Evaluate and compose functions" },
  { id:"2013-jan-4H-24", year:2013, session:"January", paper:"4H", questionNumber:24, marks:3, topics:["Percentages","Speed"], difficulty:"Hard", summary:"Percentage reduction in travel time" },
  { id:"2013-jan-4H-25", year:2013, session:"January", paper:"4H", questionNumber:25, marks:6, topics:["Trigonometry"], difficulty:"Hard", summary:"Flagpole angle of elevation" },
  { id:"2013-jan-4H-26", year:2013, session:"January", paper:"4H", questionNumber:26, marks:6, topics:["Simultaneous Equations","Quadratics"], difficulty:"Hard", summary:"Simultaneous nonlinear equations" },
];
